Fix argmax for ChainedVector with function 1st arg
JuliaData/SentinelArrays.jl pull request #59
Opened 2021-08-03 03:42 UTC by quinnj

Fixes #51.

2021-08-03 07:17 UTC, bkamins requested changes
I think it is not the point of this change, see the example on Julia 1.7:
```
julia> argmax(abs, -10:5)
-10
```
so a value from domain is returned. With your fix you would return a value from co-domain:
```
julia> argmax(abs, ChainedVector([-10:5])) # this is after your change
10
```
and before your change we have:
```
```
julia> argmax(abs, ChainedVector([-10:5])) # this is before your change
1
```

2021-08-03 12:34 UTC, quinnj commented
Ah, now it makes sense; I kept feeling I was just not getting this whole issue; thanks for the example. The code now should be correct.

2021-08-03 13:02 UTC, nickrobinson251 commented on src/chainedvector.jl
> +Base.argmin(f::F, x::ChainedVector) where {F} = x[findmin(f, x)[2]]
why doesn't Base have these definitions? i.e. just forward `argmin` -> `findmin` (at least for AbstractArrays)

2021-08-03 14:17 UTC, bkamins commented on src/chainedvector.jl
> +Base.argmin(f::F, x::ChainedVector) where {F} = x[findmin(f, x)[2]]
I think the reason is that in Base `domain` can be more general, and in particular do not implement `findmax`.

2021-08-03 14:18 UTC, bkamins approved these changes
looks good now

2021-08-03 14:28 UTC, nickrobinson251 commented on src/chainedvector.jl
> +Base.argmin(f::F, x::ChainedVector) where {F} = x[findmin(f, x)[2]]
interesting, i'll follow-up on the Julia repo or slack

it looks to me like Base has a default `findmax(A::AbstractArray)` method, and also that an `AbstractArray` is required to implement `getindex`, and these are the only things needed to get `argmax` for free :) 

(anyway, this was just a curiosity -- PR looks good to me too!)

2021-08-03 14:30 UTC, nickrobinson251 commented on src/chainedvector.jl
> +Base.argmin(f::F, x::ChainedVector) where {F} = x[findmin(f, x)[2]]
oh, i was looking at pre-1.7 Base code, i see how it's changed now -- thanks for the discussion :)

2021-08-03 15:39 UTC, merged

2022-10-05 05:23 UTC, quinnj commented
We match Base's behavior here?
```julia
julia> a = collect(20:40)
21-element Vector{Int64}:
 20
 21
 22
 23
 24
 25
 26
 27
 28
 29
 30
 31
 32
 33
 34
 35
 36
 37
 38
 39
 40

julia> argmax(a; dims=(1,))
1-element Vector{Int64}:
 21

julia> b = ChainedVector([a])
21-element ChainedVector{Int64, Vector{Int64}}:
 20
 21
 22
 23
 24
 25
 26
 27
 28
 29
 30
 31
 32
 33
 34
 35
 36
 37
 38
 39
 40

julia> argmax(b; dims=(1,))
1-element Vector{Int64}:
 21
```